# Generated by Django 4.2.16 on 2024-12-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiazure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='horarys',
            field=models.ManyToManyField(db_index=True, related_name='horaryvoluntary', to='apiazure.horary'),
        ),
    ]
