# Generated by Django 4.2.16 on 2024-11-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiazure', '0002_event_alter_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiazure.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
