# Generated by Django 4.2.16 on 2024-12-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiazure', '0002_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='organizator',
        ),
    ]
