# Generated by Django 4.2.16 on 2024-12-08 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiazure', '0003_remove_invite_organizator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='uservoluntary', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
