# Generated by Django 4.2.16 on 2024-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiazure', '0003_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='isactive',
        ),
    ]
