# Generated by Django 4.2.16 on 2025-02-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiazure', '0003_follow_notiys_alter_follow_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiazure.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='waitparticipant',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_wait'),
        ),
    ]
